name: rooster rust tests

on: pull_request

jobs:
  rust-linux-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: sudo apt install curl unzip pkg-config libxcb-render0-dev libxcb-shape0-dev libxcb-xfixes0-dev libx11-dev libxmu-dev python3 libssl-dev libsodium-dev xsel
      - name: Checkout code
        uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        name: Install rust
        with:
          toolchain: stable
      - uses: actions-rs/cargo@v1
        name: Run cargo test
        with:
          command: test
          args: --all-targets --all-features --manifest-path Cargo.toml
